services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true