server {
    listen 80;
    server_name devponcet07.fr www.devponcet07.fr;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;

    server_name devponcet07.fr www.devponcet07.fr;

    ssl_certificate /etc/letsencrypt/live/devponcet07.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/devponcet07.fr/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}